--------------------------------------------------------
--  파일이 생성됨 - 화요일-5월-17-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "PROJECT"."PRODUCT" 
   (	"PSEQ" NUMBER(5,0), 
	"NAME" VARCHAR2(100 BYTE), 
	"KIND" CHAR(1 BYTE), 
	"PRICE1" NUMBER(7,0) DEFAULT '0', 
	"PRICE2" NUMBER(7,0) DEFAULT '0', 
	"PRICE3" NUMBER(7,0) DEFAULT '0', 
	"CONTENT" VARCHAR2(2000 CHAR), 
	"IMAGE" VARCHAR2(200 CHAR) DEFAULT 'default.jpg', 
	"THUMB_IMAGE" VARCHAR2(200 CHAR) DEFAULT 'default.jpg', 
	"USEYN" CHAR(1 BYTE) DEFAULT 'y', 
	"BESTYN" CHAR(1 BYTE) DEFAULT 'n', 
	"INDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into PROJECT.PRODUCT
SET DEFINE OFF;
Insert into PROJECT.PRODUCT (PSEQ,NAME,KIND,PRICE1,PRICE2,PRICE3,CONTENT,IMAGE,THUMB_IMAGE,USEYN,BESTYN,INDATE) values (1,'크로그다일부츠','2',40000,50000,10000,'오리지날 크로그다일부츠 입니다.','w2.jpg','w2.jpg','y','y',to_date('22/04/05','RR/MM/DD'));
Insert into PROJECT.PRODUCT (PSEQ,NAME,KIND,PRICE1,PRICE2,PRICE3,CONTENT,IMAGE,THUMB_IMAGE,USEYN,BESTYN,INDATE) values (2,'롱부츠','2',40000,50000,10000,'따뜻한 롱부츠 입니다.','w-28.jpg','w-28.jpg','y','n',to_date('22/04/05','RR/MM/DD'));
Insert into PROJECT.PRODUCT (PSEQ,NAME,KIND,PRICE1,PRICE2,PRICE3,CONTENT,IMAGE,THUMB_IMAGE,USEYN,BESTYN,INDATE) values (3,'힐','1',10000,12000,2000,'여성용전용 힐','w-26.jpg','w-26.jpg','y','n',to_date('22/04/05','RR/MM/DD'));
Insert into PROJECT.PRODUCT (PSEQ,NAME,KIND,PRICE1,PRICE2,PRICE3,CONTENT,IMAGE,THUMB_IMAGE,USEYN,BESTYN,INDATE) values (4,'슬리퍼','4',5000,5500,500,'편안한 슬리퍼입니다.','w-25.jpg','w-25.jpg','y','y',to_date('22/04/05','RR/MM/DD'));
Insert into PROJECT.PRODUCT (PSEQ,NAME,KIND,PRICE1,PRICE2,PRICE3,CONTENT,IMAGE,THUMB_IMAGE,USEYN,BESTYN,INDATE) values (5,'회색힐','1',10000,12000,2000,'여성용전용 힐','w9.jpg','w-09.jpg','y','n',to_date('22/04/05','RR/MM/DD'));
Insert into PROJECT.PRODUCT (PSEQ,NAME,KIND,PRICE1,PRICE2,PRICE3,CONTENT,IMAGE,THUMB_IMAGE,USEYN,BESTYN,INDATE) values (6,'여성부츠','2',12000,18000,6000,'여성용 부츠','w4.jpg','w-04.jpg','y','n',to_date('22/04/05','RR/MM/DD'));
Insert into PROJECT.PRODUCT (PSEQ,NAME,KIND,PRICE1,PRICE2,PRICE3,CONTENT,IMAGE,THUMB_IMAGE,USEYN,BESTYN,INDATE) values (7,'핑크샌달','3',5000,5500,500,'사계절용 샌달입니다.','w-10.jpg','w-10.jpg','y','y',to_date('22/04/05','RR/MM/DD'));
Insert into PROJECT.PRODUCT (PSEQ,NAME,KIND,PRICE1,PRICE2,PRICE3,CONTENT,IMAGE,THUMB_IMAGE,USEYN,BESTYN,INDATE) values (8,'슬리퍼','3',5000,5500,500,'편안한 슬리퍼입니다.','w11.jpg','w11.jpg','y','y',to_date('22/04/05','RR/MM/DD'));
Insert into PROJECT.PRODUCT (PSEQ,NAME,KIND,PRICE1,PRICE2,PRICE3,CONTENT,IMAGE,THUMB_IMAGE,USEYN,BESTYN,INDATE) values (9,'스니커즈','4',15000,20000,5000,'활동성이 좋은 스니커즈입니다.','w1.jpg','w1.jpg','y','n',to_date('22/04/05','RR/MM/DD'));
Insert into PROJECT.PRODUCT (PSEQ,NAME,KIND,PRICE1,PRICE2,PRICE3,CONTENT,IMAGE,THUMB_IMAGE,USEYN,BESTYN,INDATE) values (21,'스니커즈','5',15000,20000,5000,'활동성이 좋은 스니커즈입니다.','w-05.jpg','w-26.jpg','y','n',to_date('22/04/11','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C007144
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."SYS_C007144" ON "PROJECT"."PRODUCT" ("PSEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "PROJECT"."PRODUCT" ADD PRIMARY KEY ("PSEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
